<script src="https://browser.sentry-cdn.com/6.7.2/bundle.min.js" integrity="sha384-mH9XMETXlBjvLoIIA0do4C9E+wHcMwicM3W3ppIqBJvJq+ge8XBvyY6Of1GcSjIQ" crossorigin="anonymous"></script>

<script>
    Sentry.init({
        dsn: "https://60e4bc6f7eaf46a0a4ff61e8a3081bd2@o245711.ingest.sentry.io/5828381",
        release: "Magento2",
        integrations: [new Sentry.Integrations.BrowserTracing()],
        tracesSampleRate: 1.0,
    });
</script>

<script>
    require([
        'jquery',
        'Porthas_MightyForms/js/dataTables.min'
    ], function($) {

        try {

            jQuery(document).ready(function() {
                jQuery('#user_forms').DataTable();



                jQuery('#mf-table-header button').on('click', function() {

                    let confirmDialog = confirm('Are you sure you want to remove the API key?');

                    if (confirmDialog) {
                        jQuery.ajax({
                                method: "POST",
                                url: '<?php echo $block->getUrl("porthas_mightyforms/apikey/index/"); ?>' + '?isAjax=true',
                                dataType: 'json',
                                data: {
                                    apiKey: 'reconnect',
                                    form_key: window.FORM_KEY
                                }
                            })
                            .done(function(msg) {
                                alert('API key was resetted. Now, you can go to Mightyforms -> Application, logout from your current account and sign in to another')
                            })
                            .error(function(msg) {
                                throw new Error(msg);
                            });
                    }

                });
            });
        } catch (error) {
            Sentry.captureException(error);
        }
    });
</script>

<style>
    #mf-table-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    #mf-table-header button {
        color: #fff;
        border: 0;
        padding: 6px 8px;
        border-radius: 3px;
        background-color: #dc3545;
        cursor: pointer;
        outline: none;
    }

    #mf-table-header button:hover {
        background-color: #ca2a39;
    }

    .mf-warning {
        border: 1px solid orange;
        padding: 10px;
        background: #ff8d001f;
        border-radius: 4px;
    }
</style>

<!-- Google Tag Manager -->
<script>
    (function(w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start': new Date().getTime(),
            event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s),
            dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-MW39298');
</script>
<!-- End Google Tag Manager -->


<?php

$forms_block = $block
    ->getLayout()
    ->createBlock('Porthas\MightyForms\Block\Adminhtml\Forms');

$user_forms_json = $forms_block->getFormsList();

$user_forms_array = json_decode($user_forms_json, true);

if (!$user_forms_array['success']) {

    echo '<h4 class="mf-warning">
    You need to create at least one form in order to be able to embed them on the site.
    To do this, go to the "Application" tab or visit the <a href="https://app.mightyforms.com" target="_blank">application website</a></h4>';
} elseif (isset($user_forms_array) && $user_forms_array['success'] && count($user_forms_array['data']) < 1) {

    echo '<h4 class="mf-warning">You have not created form yet </h4>';
} else { ?>

    <table id="user_forms" class="display">
        <thead>
            <tr>
                <td>Form name</td>
                <td>Shortcode</td>
                <td>Last editor</td>
                <td>Last modified</td>
            </tr>
            <div id="mf-table-header">
                <h3>Your forms and shortcodes.</h3>
                <button>Reconnect</button>
            </div>

            <p>If you want to show your form in a page or post - just copy the form's shortcode and paste it into your
                visual editor. That's it!</p>
        </thead>
        <tbody>

            <?php foreach ($user_forms_array['data'] as $forms) { ?>
                <tr>
                    <td><?= $forms['project_name'] ?></td>
                    <td> {{block class="Porthas\MightyForms\Block\EmbeddedBlock" name="render_form"
                        form_id="<?php echo $forms['project_id']; ?>" template="Porthas_MightyForms::form.phtml"}}
                    </td>
                    <td> <?= isset($forms['last_modified_username']) ? $forms['last_modified_username'] : '' ?></td>
                    <td> <?= isset($forms['last_modified']) ? $forms['last_modified'] : '' ?></td>
                </tr>
            <?php } ?>

        </tbody>
    </table>

<?php } ?>