<script>
    require([
        'jquery',
        'Porthas_MightyForms/js/dataTables.min'
    ], function ($) {

        $(document).ready(function () {
            jQuery('#user_forms').DataTable();
        });
    });
</script>

<?php

    $forms_block = $block
        ->getLayout()
        ->createBlock('Porthas\MightyForms\Block\Adminhtml\Forms');

    $user_forms_json = $forms_block->getFormsList();

    $user_forms_array = json_decode($user_forms_json, true);

    if (!$user_forms_array['success']) {

        echo '<h4> Error occurred. Message: ' . $user_forms_array['error'] . ' </h4>';

    } elseif (isset($user_forms_array) && $user_forms_array['success'] && count($user_forms_array['data']) < 1) {

        echo '<h4>You have not created form yet </h4>';

    } else { ?>

        <table id="user_forms" class="display">
            <thead>
            <tr>
                <td>Form name</td>
                <td>Shortcode</td>
                <td>Last editor</td>
                <td>Last modified</td>
            </tr>
            <h3>Your forms and shortcodes.</h3>
            <p>If you want to show your form in a page or post - just copy the form's shortcode and paste it into your
                visual editor. That's it!</p>
            </thead>
            <tbody>

            <?php foreach ($user_forms_array['data'] as $forms) { ?>
                <tr>
                    <td><?= $forms['project_name'] ?></td>
                    <td> {{block class="Porthas\MightyForms\Block\EmbeddedBlock" name="render_form"
                        form_id="<?php echo $forms['project_id']; ?>" template="Porthas_MightyForms::form.phtml"}}
                    </td>
                    <td> <?= isset($forms['last_modified_username']) ? $forms['last_modified_username'] : '' ?></td>
                    <td> <?= isset($forms['last_modified']) ? $forms['last_modified'] : '' ?></td>
                </tr>
            <?php } ?>

            </tbody>
        </table>

<?php } ?>

