<script>

    require(['jquery', 'mage/url'], function ($) {
        $(document).ready(function () {

            $(window).on('message', function (e) {

                let rawData = e.originalEvent.data;

                try {
                    if (typeof rawData !== 'string') return;

                    let post = JSON.parse(rawData);

                    if ('userApiKey' === post.message) {

                        console.log('This is key:', post.data);

                        $.ajax({
                            method: "POST",
                            url: '<?php echo $block->getUrl("porthas_mightyforms/apikey/index/");?>' + '?isAjax=true',
                            dataType: 'json',
                            data: {
                                apiKey: post.data,
                                form_key: window.FORM_KEY
                            }
                        })
                            .done(function (msg) {
                                console.log("Data Saved: ", msg);
                            })
                            .error(function (msg) {
                                throw new Exception(msg);
                            });
                    }
                } catch (e) {
                    console.log(`Error occurred in attempt to save API key to database. Please, contact with support of MightyForms. Message:  ${JSON.stringify(e)}`);
                }
            });
        });
    });

</script>


<iframe src="https://app.mightyforms.com" id="mightyforms" style="width:100%; height: 100%;"  frameborder="0"></iframe>